// backend/utils/trainingData.js
// Expanded training data for BrainBytes AI across subjects

const trainingData = [
  // ===== MATH =====
  { input: "What is a fraction?", output: "A fraction represents a part of a whole. It has two parts: the numerator (top number) shows how many parts you have, and the denominator (bottom number) shows how many equal parts the whole is divided into. Example: 3/4 means 3 out of 4 equal parts.", type: "definition", subject: "Math" },
  { input: "How do you add fractions?", output: "To add fractions: (1) Make the denominators the same (find the LCD). (2) Add the numerators. (3) Keep the denominator. (4) Simplify if needed. Example: 1/4 + 2/4 = 3/4.", type: "explanation", subject: "Math" },
  { input: "Give me an example of algebra", output: "Sure! Algebra uses variables to solve problems. Example: If x + 3 = 7, what is x? Subtract 3 from both sides: x = 7 - 3 = 4. We solved for the unknown value x!", type: "example", subject: "Math" },
  { input: "What is the Pythagorean theorem?", output: "The Pythagorean theorem states that in a right triangle, the square of the hypotenuse (longest side) equals the sum of the squares of the other two sides: a² + b² = c². Example: if a=3 and b=4, then c=5 because 9+16=25.", type: "definition", subject: "Math" },
  { input: "What is a percentage?", output: "A percentage is a way of expressing a number as a fraction of 100. The symbol is %. Example: 50% means 50 out of 100, which is the same as 1/2 or 0.5.", type: "definition", subject: "Math" },

  // ===== SCIENCE =====
  { input: "What is photosynthesis?", output: "Photosynthesis is the process plants use to make food. They absorb sunlight, water, and carbon dioxide, then convert them into glucose (sugar) and oxygen. Formula: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂.", type: "definition", subject: "Science" },
  { input: "How does gravity work?", output: "Gravity is a force that attracts objects with mass toward each other. The more mass an object has, the stronger its gravitational pull. Earth's gravity pulls everything toward its center, which is why objects fall down when dropped.", type: "explanation", subject: "Science" },
  { input: "What is an atom?", output: "An atom is the smallest unit of matter that retains the properties of an element. It has a nucleus (containing protons and neutrons) surrounded by electrons orbiting in shells. Everything around us is made of atoms!", type: "definition", subject: "Science" },
  { input: "Give me an example of a chemical reaction", output: "A great example is burning wood. Wood (carbon-based) reacts with oxygen in the air to produce carbon dioxide, water vapor, and heat energy. Another example: baking soda + vinegar → bubbles of CO₂ gas!", type: "example", subject: "Science" },
  { input: "What is the difference between a cell and an atom?", output: "An atom is the smallest unit of matter (like a single Lego brick). A cell is the smallest unit of life, made up of billions of atoms. Cells contain water, proteins, DNA, and more. Atoms are to cells what bricks are to a house.", type: "explanation", subject: "Science" },
  { input: "What are the states of matter?", output: "There are four main states of matter: Solid (fixed shape and volume, e.g., ice), Liquid (fixed volume but takes shape of container, e.g., water), Gas (no fixed shape or volume, e.g., steam), and Plasma (high-energy ionized gas, e.g., the sun).", type: "definition", subject: "Science" },

  // ===== PROGRAMMING =====
  { input: "What is a variable?", output: "A variable is a named container that stores a value in a program. Think of it like a labeled box — you can put a value in it, look at it, or change it. Example in JavaScript: let age = 18; — here 'age' is the variable holding the value 18.", type: "definition", subject: "Programming" },
  { input: "How does a for loop work?", output: "A for loop repeats a block of code a set number of times. It has 3 parts: (1) initialization — start value, (2) condition — keep looping while this is true, (3) update — change the counter each time. Example: for(let i=0; i<5; i++) { console.log(i); } prints 0,1,2,3,4.", type: "explanation", subject: "Programming" },
  { input: "What is a function?", output: "A function is a reusable block of code that performs a specific task. You define it once and can call it many times. Example: function greet(name) { return 'Hello, ' + name; } — calling greet('Maria') returns 'Hello, Maria'.", type: "definition", subject: "Programming" },
  { input: "Give me an example of an array", output: "An array stores multiple values in one variable. Example in JavaScript: let fruits = ['apple', 'banana', 'mango']; — fruits[0] gives 'apple', fruits[1] gives 'banana'. Arrays are great for storing lists!", type: "example", subject: "Programming" },
  { input: "What is debugging?", output: "Debugging is the process of finding and fixing errors (bugs) in your code. Tools include console.log() to print values, browser DevTools, or a debugger. A bug is any mistake that causes your program to behave incorrectly.", type: "definition", subject: "Programming" },

  // ===== ENGLISH =====
  { input: "What is a noun?", output: "A noun is a word that names a person, place, thing, or idea. Examples: teacher (person), school (place), book (thing), freedom (idea). Nouns are one of the most basic parts of speech in English.", type: "definition", subject: "English" },
  { input: "What is the difference between affect and effect?", output: "'Affect' is usually a verb meaning to influence something. 'Effect' is usually a noun meaning the result. Memory trick: Affect = Action (verb), Effect = End result (noun). Example: The rain affected our plans. The effect of rain was a cancelled trip.", type: "explanation", subject: "English" },
  { input: "Give me an example of a simile", output: "A simile compares two things using 'like' or 'as'. Examples: 'She runs like the wind.' / 'He is as brave as a lion.' / 'The water was as cold as ice.' Similes make writing more vivid and descriptive!", type: "example", subject: "English" },

  // ===== HISTORY =====
  { input: "What caused World War 1?", output: "WWI was caused by several factors, often remembered as MAIN: Militarism (arms race between nations), Alliances (tangled treaty obligations), Imperialism (competition over colonies), and Nationalism (rising pride and tensions). The spark was the assassination of Archduke Franz Ferdinand in 1914.", type: "explanation", subject: "History" },
  { input: "What was the Industrial Revolution?", output: "The Industrial Revolution (roughly 1760–1840) was a period of major change when manufacturing shifted from hand production to machine-based factory work. It began in Britain and spread worldwide. Key inventions included the steam engine and power loom, transforming economies and cities.", type: "definition", subject: "History" },

  // ===== MATH =====
  { input: "What is a prime number?", output: "A prime number is a number greater than 1 that has no divisors other than 1 and itself. Examples: 2, 3, 5, 7, 11, 13. The number 2 is the only even prime number. Non-prime numbers are called composite numbers.", type: "definition", subject: "Math" },
  { input: "How do you multiply fractions?", output: "To multiply fractions: (1) Multiply the numerators together. (2) Multiply the denominators together. (3) Simplify if needed. Example: 2/3 × 3/4 = (2×3)/(3×4) = 6/12 = 1/2. No need to find a common denominator!", type: "explanation", subject: "Math" },
  { input: "What is the order of operations?", output: "Order of operations tells you which calculations to do first. Remember PEMDAS: Parentheses, Exponents, Multiplication & Division (left to right), Addition & Subtraction (left to right). Example: 2 + 3 × 4 = 2 + 12 = 14 (not 20).", type: "definition", subject: "Math" },
  { input: "What is a negative number?", output: "A negative number is any number less than zero. It has a minus sign (−) in front of it. Example: −5 is 5 units below zero. Negative numbers are used in temperatures (−10°C), debt (−$50), and elevations below sea level.", type: "definition", subject: "Math" },
  { input: "How do you find the area of a rectangle?", output: "The area of a rectangle = length × width. Example: A rectangle that is 5 cm long and 3 cm wide has an area of 5 × 3 = 15 cm². Area is always measured in square units like cm², m², or ft².", type: "explanation", subject: "Math" },
  { input: "What is a square root?", output: "A square root of a number is a value that, when multiplied by itself, gives the original number. Symbol: √. Example: √25 = 5 because 5 × 5 = 25. √9 = 3 because 3 × 3 = 9.", type: "definition", subject: "Math" },
  { input: "What is mean, median, and mode?", output: "These are measures of central tendency. Mean = average (sum ÷ count). Median = the middle value when sorted. Mode = the value that appears most often. Example for [2, 3, 3, 4, 8]: Mean=4, Median=3, Mode=3.", type: "explanation", subject: "Math" },
  { input: "What is a ratio?", output: "A ratio compares two quantities. Written as a:b or a/b. Example: If there are 3 apples and 5 oranges, the ratio of apples to oranges is 3:5. Ratios are used in recipes, maps, and scaling drawings.", type: "definition", subject: "Math" },
  { input: "How do you solve an equation with two variables?", output: "You need two equations (a system). Method: substitution or elimination. Example: x + y = 10 and x − y = 2. Add both: 2x = 12, so x = 6. Substitute back: 6 + y = 10, so y = 4.", type: "explanation", subject: "Math" },
  { input: "What is a graph in math?", output: "A graph visually represents data or mathematical relationships. Common types: bar graph (comparing categories), line graph (showing trends), and coordinate graph (plotting points using x and y axes). Graphs make data easier to understand.", type: "definition", subject: "Math" },
  { input: "What is probability?", output: "Probability measures how likely an event is to happen. It ranges from 0 (impossible) to 1 (certain). Formula: P(event) = favorable outcomes ÷ total outcomes. Example: The probability of rolling a 3 on a die = 1/6.", type: "definition", subject: "Math" },
  { input: "Give me an example of probability", output: "If you flip a fair coin, there are 2 possible outcomes: heads or tails. The probability of getting heads = 1/2 = 50%. If you draw a red card from a standard deck of 52 cards, P(red) = 26/52 = 1/2.", type: "example", subject: "Math" },
 
  // ===== SCIENCE =====
  { input: "What are the states of matter?", output: "There are four main states of matter: Solid (fixed shape and volume, e.g., ice), Liquid (fixed volume but takes shape of container, e.g., water), Gas (no fixed shape or volume, e.g., steam), and Plasma (high-energy ionized gas, e.g., the sun).", type: "definition", subject: "Science" },
  { input: "What is the water cycle?", output: "The water cycle describes how water moves through the environment. Steps: (1) Evaporation — water turns to vapor from heat. (2) Condensation — vapor cools and forms clouds. (3) Precipitation — rain or snow falls. (4) Collection — water gathers in oceans, lakes, rivers.", type: "explanation", subject: "Science" },
  { input: "What is DNA?", output: "DNA (Deoxyribonucleic Acid) is the molecule that carries genetic instructions for the development and functioning of living things. It's shaped like a double helix (twisted ladder). DNA is found in the nucleus of every cell and determines traits like eye color.", type: "definition", subject: "Science" },
  { input: "What is Newton's first law of motion?", output: "Newton's first law states that an object at rest stays at rest, and an object in motion stays in motion at the same speed and direction, unless acted on by an external force. This is also called the Law of Inertia.", type: "definition", subject: "Science" },
  { input: "What is Newton's second law of motion?", output: "Newton's second law states that Force = Mass × Acceleration (F = ma). The greater the mass of an object, the more force needed to accelerate it. Example: Pushing a heavy cart requires more force than pushing a light one.", type: "definition", subject: "Science" },
  { input: "What is Newton's third law of motion?", output: "Newton's third law states that for every action, there is an equal and opposite reaction. Example: When you push off the ground while jumping, the ground pushes back with equal force — launching you upward.", type: "definition", subject: "Science" },
  { input: "What is the difference between physical and chemical change?", output: "A physical change alters the form but not the substance (e.g., cutting paper, melting ice). A chemical change produces a new substance (e.g., burning wood, rusting iron). Key sign of a chemical change: color change, gas produced, or heat released.", type: "explanation", subject: "Science" },
  { input: "What is an ecosystem?", output: "An ecosystem is a community of living organisms (plants, animals, microbes) interacting with each other and their environment (soil, water, air). Examples: a forest, coral reef, or desert. Each part plays a role in keeping the ecosystem balanced.", type: "definition", subject: "Science" },
  { input: "What is the speed of light?", output: "The speed of light in a vacuum is approximately 299,792,458 meters per second (about 300,000 km/s). Nothing in the universe travels faster than light. It takes about 8 minutes for light from the Sun to reach Earth.", type: "definition", subject: "Science" },
  { input: "What is the periodic table?", output: "The periodic table is a chart of all known chemical elements arranged by atomic number. Each element has a symbol (e.g., H for Hydrogen, O for Oxygen). Elements are grouped by similar properties — metals, nonmetals, and metalloids.", type: "definition", subject: "Science" },
  { input: "What causes seasons?", output: "Seasons are caused by Earth's tilt (23.5°) as it orbits the Sun, not by its distance. When the Northern Hemisphere tilts toward the Sun, it gets summer. When it tilts away, it gets winter. The Southern Hemisphere experiences the opposite at the same time.", type: "explanation", subject: "Science" },
  { input: "What is energy?", output: "Energy is the ability to do work or cause change. It comes in many forms: kinetic (motion), potential (stored), thermal (heat), chemical, electrical, and nuclear. Energy can be converted from one form to another but cannot be created or destroyed (Law of Conservation of Energy).", type: "definition", subject: "Science" },
 
  // ===== PROGRAMMING =====
  { input: "What is an object in programming?", output: "An object is a collection of related data and functions grouped together. It has properties (data) and methods (actions). Example in JavaScript: let dog = { name: 'Buddy', breed: 'Labrador', bark: function() { return 'Woof!'; } };", type: "definition", subject: "Programming" },
  { input: "What is a class in programming?", output: "A class is a blueprint for creating objects. It defines properties and methods that its objects will have. Example: class Car { constructor(brand) { this.brand = brand; } drive() { return this.brand + ' is moving!'; } } let myCar = new Car('Toyota');", type: "definition", subject: "Programming" },
  { input: "What is the difference between == and === in JavaScript?", output: "== checks if values are equal but ignores data type (loose equality). === checks if values AND types are equal (strict equality). Example: '5' == 5 is true, but '5' === 5 is false. Always prefer === to avoid unexpected bugs.", type: "explanation", subject: "Programming" },
  { input: "What is a conditional statement?", output: "A conditional statement runs code only if a condition is true. Example: if (score >= 75) { console.log('Passed!'); } else { console.log('Failed.'); } It uses if, else if, and else to handle different situations.", type: "definition", subject: "Programming" },
  { input: "What is a while loop?", output: "A while loop repeats code as long as a condition is true. Example: let i = 0; while (i < 3) { console.log(i); i++; } This prints 0, 1, 2. Be careful — if the condition never becomes false, you get an infinite loop!", type: "explanation", subject: "Programming" },
  { input: "What is recursion?", output: "Recursion is when a function calls itself to solve a smaller version of the same problem. Example: function factorial(n) { if (n === 1) return 1; return n * factorial(n - 1); } factorial(5) = 5×4×3×2×1 = 120.", type: "definition", subject: "Programming" },
  { input: "What is an API?", output: "An API (Application Programming Interface) is a way for two programs to communicate. It defines rules for requesting and sending data. Example: A weather app uses a weather API to fetch current temperatures. APIs use HTTP requests like GET and POST.", type: "definition", subject: "Programming" },
  { input: "What is JSON?", output: "JSON (JavaScript Object Notation) is a lightweight format for storing and transporting data. It's easy for humans to read and for machines to parse. Example: { \"name\": \"Maria\", \"age\": 20, \"subjects\": [\"Math\", \"Science\"] }", type: "definition", subject: "Programming" },
  { input: "What is the difference between let, const, and var?", output: "var is function-scoped and can be re-declared (avoid in modern JS). let is block-scoped and can be reassigned. const is block-scoped and cannot be reassigned after declaration. Best practice: use const by default, let when you need to reassign.", type: "explanation", subject: "Programming" },
  { input: "What is a callback function?", output: "A callback function is a function passed as an argument to another function, to be called later. Example: setTimeout(function() { console.log('Hello after 2 seconds!'); }, 2000); The anonymous function is the callback — it runs after the delay.", type: "definition", subject: "Programming" },
  { input: "What is Git?", output: "Git is a version control system that tracks changes to your code over time. It lets you save snapshots (commits), create branches to work on features, and collaborate with others. Common commands: git init, git add, git commit, git push, git pull.", type: "definition", subject: "Programming" },
  { input: "What is a database?", output: "A database is an organized collection of structured data stored electronically. Types include relational (SQL, like MySQL) and non-relational (NoSQL, like MongoDB). Databases allow you to create, read, update, and delete data — known as CRUD operations.", type: "definition", subject: "Programming" },
 
  // ===== ENGLISH =====
  { input: "What is a verb?", output: "A verb is a word that expresses an action, occurrence, or state of being. Examples: run, jump, think, is, are, seems. Every complete sentence needs a subject and a verb. Verbs can be in different tenses: past, present, and future.", type: "definition", subject: "English" },
  { input: "What is an adjective?", output: "An adjective is a word that describes or modifies a noun. It gives more information about a person, place, or thing. Examples: 'The tall building', 'a red apple', 'three happy children'. Adjectives answer: What kind? How many? Which one?", type: "definition", subject: "English" },
  { input: "What is an adverb?", output: "An adverb modifies a verb, adjective, or another adverb. It answers how, when, where, or to what extent. Many end in -ly. Examples: 'She runs quickly', 'He spoke very softly', 'They arrived early'. Adverbs add detail to actions.", type: "definition", subject: "English" },
  { input: "What is the difference between a metaphor and a simile?", output: "Both compare two things, but differently. A simile uses 'like' or 'as': 'Life is like a journey.' A metaphor makes a direct comparison without 'like' or 'as': 'Life is a journey.' Metaphors are often more powerful and direct.", type: "explanation", subject: "English" },
  { input: "What is a thesis statement?", output: "A thesis statement is the main argument or central point of an essay, usually placed at the end of the introduction. It tells the reader what you will argue and why. Example: 'Social media negatively affects teenage mental health by promoting unrealistic comparisons.'", type: "definition", subject: "English" },
  { input: "What is active and passive voice?", output: "In active voice, the subject performs the action: 'The dog chased the ball.' In passive voice, the subject receives the action: 'The ball was chased by the dog.' Active voice is clearer and more direct. Use passive voice sparingly.", type: "explanation", subject: "English" },
  { input: "What is a pronoun?", output: "A pronoun replaces a noun to avoid repetition. Examples: I, you, he, she, it, we, they, me, him, her, us, them. Instead of 'Maria went to Maria's class', we say 'Maria went to her class.' Pronouns make sentences smoother.", type: "definition", subject: "English" },
  { input: "What is alliteration?", output: "Alliteration is the repetition of the same consonant sound at the beginning of nearby words. Examples: 'Peter Piper picked a peck', 'She sells seashells by the seashore'. It's used in poetry, slogans, and literature to create rhythm and emphasis.", type: "definition", subject: "English" },
  { input: "What is a paragraph?", output: "A paragraph is a group of related sentences about one main idea. It typically has: a topic sentence (main idea), supporting sentences (details/evidence), and a concluding sentence (wrap-up). A good paragraph is focused, coherent, and well-developed.", type: "definition", subject: "English" },
  { input: "What are the types of sentences?", output: "There are 4 types: Declarative (makes a statement: 'The sky is blue.'), Interrogative (asks a question: 'Is it raining?'), Imperative (gives a command: 'Close the door.'), and Exclamatory (expresses strong emotion: 'What a great day!')", type: "explanation", subject: "English" },
 
  // ===== HISTORY =====
  { input: "What was World War 2?", output: "World War 2 (1939–1945) was the deadliest conflict in history, involving most of the world's nations. It was fought between the Allies (USA, UK, USSR, France) and the Axis powers (Germany, Italy, Japan). It ended with the defeat of Nazi Germany and Japan, and led to the formation of the United Nations.", type: "explanation", subject: "History" },
  { input: "Who was Jose Rizal?", output: "Jose Rizal (1861–1896) was a Filipino national hero, doctor, and writer. He wrote Noli Me Tangere and El Filibusterismo, which exposed the abuses of Spanish colonial rule and inspired the Philippine Revolution. He was executed by the Spaniards on December 30, 1896.", type: "definition", subject: "History" },
  { input: "What was the Cold War?", output: "The Cold War (1947–1991) was a period of geopolitical tension between the USA and the Soviet Union. It was called 'cold' because there was no direct military conflict. Instead, both sides competed through the arms race, space race, and proxy wars. It ended with the collapse of the Soviet Union in 1991.", type: "explanation", subject: "History" },
  { input: "What was the French Revolution?", output: "The French Revolution (1789–1799) was a period of radical political change in France where the monarchy was overthrown and a republic was established. Key causes: inequality, heavy taxes, and Enlightenment ideas. Key events: storming of the Bastille, Declaration of the Rights of Man, and the rise of Napoleon.", type: "explanation", subject: "History" },
  { input: "What is colonialism?", output: "Colonialism is when one country takes control of another territory, governing and exploiting it for resources and profit. European powers like Spain, Britain, and France colonized much of Asia, Africa, and the Americas from the 1400s–1900s. Colonialism had lasting effects on culture, economy, and identity.", type: "definition", subject: "History" },
  { input: "What was the Renaissance?", output: "The Renaissance (roughly 14th–17th century) was a cultural and intellectual movement that began in Italy and spread across Europe. It marked a revival of art, science, and literature inspired by ancient Greek and Roman ideas. Key figures: Leonardo da Vinci, Michelangelo, Galileo, and Shakespeare.", type: "definition", subject: "History" },
  { input: "What was the Philippine Revolution?", output: "The Philippine Revolution (1896–1898) was the uprising of Filipino people against Spanish colonial rule. Led by the Katipunan, founded by Andres Bonifacio, it was inspired by the writings of Jose Rizal. It led to the declaration of Philippine independence on June 12, 1898.", type: "explanation", subject: "History" },
  { input: "Who was Andres Bonifacio?", output: "Andres Bonifacio (1863–1897) was a Filipino revolutionary leader and founder of the Katipunan, a secret society that led the fight against Spanish colonization. Known as the 'Father of the Philippine Revolution', he represented the masses and fought for immediate independence.", type: "definition", subject: "History" },
  { input: "What was the American Revolution?", output: "The American Revolution (1775–1783) was the war in which 13 American colonies fought for independence from British rule. Key causes: unfair taxation ('No taxation without representation') and lack of political rights. It resulted in the Declaration of Independence in 1776 and the birth of the United States.", type: "explanation", subject: "History" },
 
  // ===== GEOGRAPHY =====
  { input: "What are the seven continents?", output: "The seven continents are: Asia (largest), Africa (second largest), North America, South America, Antarctica (coldest), Europe, and Australia/Oceania (smallest). Remember them with: Eat An Apple As A Nighttime Snack.", type: "definition", subject: "Geography" },
  { input: "What is the largest ocean?", output: "The Pacific Ocean is the largest and deepest ocean, covering more than 30% of Earth's surface. It stretches from the Arctic in the north to the Antarctic in the south, bordered by Asia and Australia on the west and the Americas on the east.", type: "definition", subject: "Geography" },
  { input: "What is a volcano?", output: "A volcano is an opening in Earth's crust where molten rock (magma), gases, and ash can escape. When magma exits a volcano, it's called lava. Volcanoes can form mountains and islands. Examples: Mount Mayon in the Philippines, Mount Fuji in Japan.", type: "definition", subject: "Geography" },
  { input: "What is the difference between weather and climate?", output: "Weather is the short-term atmospheric conditions in a specific place — like today's rain or sunshine. Climate is the long-term average weather pattern of a region over 30+ years. Example: Manila has hot and rainy weather today, but a tropical climate overall.", type: "explanation", subject: "Geography" },
  { input: "What is latitude and longitude?", output: "Latitude measures how far north or south a location is from the equator (0°), ranging from −90° to 90°. Longitude measures how far east or west from the Prime Meridian (0°), ranging from −180° to 180°. Together, they form a coordinate system to locate any point on Earth.", type: "definition", subject: "Geography" },
  
  // ===== FILIPINO / ARALING PANLIPUNAN =====
  { input: "Ano ang Katipunan?", output: "Ang Katipunan (buong pangalan: Kataastaasang Kagalanggalangang Katipunan ng mga Anak ng Bayan) ay isang lihim na rebolusyonaryong samahan na itinatag ni Andres Bonifacio noong 1892. Layunin nito ang kalayaan ng Pilipinas mula sa pamamahala ng Espanya.", type: "definition", subject: "Filipino" },
  { input: "Sino si Emilio Aguinaldo?", output: "Si Emilio Aguinaldo (1869–1964) ang unang pangulo ng Pilipinas. Nanguna siya sa rebolusyon laban sa Espanya at nag-proklamasyon ng kalayaan ng Pilipinas noong Hunyo 12, 1898 sa Kawit, Cavite. Siya rin ay lumaban laban sa pananakop ng Amerika.", type: "definition", subject: "Filipino" },
  { input: "Ano ang Noli Me Tangere?", output: "Ang Noli Me Tangere ay isang nobelang isinulat ni Dr. Jose Rizal noong 1887. Inilalarawan nito ang mga pang-aabuso ng mga prayle at ng kolonyal na pamahalaan ng Espanya sa Pilipinas. Ang nobela ay nagbigay-inspirasyon sa mga Pilipino na lumaban para sa kalayaan.", type: "definition", subject: "Filipino" },

  ];

module.exports = trainingData;
